### ISSUE TITLE
kubernetes.repo file needs updated baseurl and gpgkey values.

### ISSUE THREAD

**Issue by aglanville** [CHernandezNY/k8s-ansible#1]
The previous package repository packages.cloud.google.com has been shutdown. The new url is pkgs.k8s.io. 
 Details on this update can be found here: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

The main.yml files under controller and worker just need these two lines updated to reflect.

baseurl=https://pkgs.k8s.io/core:/stable:/v1.26/rpm/
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.26/rpm/repodata/repomd.xml.key

**Comment by CHernandezNY** [comment]
Updated the Kubernetes roles (controller and worker) to use the new community-owned repositories.  It will derive the appropriate repository URL based on the k8s_version variable in the group_vars/all.yml.

**Comment by aglanville** [comment]
Pulled down the latest updates and it works great on the control node (rockylinux8) but the worker nodes (also rockylinux8) are seeing the same behavior.  Checking the kubernetes.repo file I see references to the google repo and the of course the downloads for kube objects fails.   

FAILED - RETRYING: [10.155.68.246]: Install Kubelet (1 retries left).
fatal: [10.155.68.245]: FAILED! => {"attempts": 10, "changed": false, "msg": "Failed to download metadata for repo 'kubernetes': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}

contents of the repo file on the worker nodes
[kubernetes]
baseurl = https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled = 1
exclude = kubelet kubeadm kubectl
gpgcheck = 1
gpgkey = https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
name = Kubernnetes
